Add old catalog help page to static site
GSA/datagov-website pull request #32
Opened 2022-03-14 15:00 UTC by nickumia-reisys

Related to https://github.com/GSA/datagov-deploy/issues/3704

2022-03-14 15:55 UTC, nickumia-reisys commented
Specific page: https://federalist-a1176d2b-cb31-49a0-ba20-a47542ee2ec5.app.cloud.gov/preview/gsa/datagov-website/catalog-help/catalog-help/

2022-03-14 16:07 UTC, FuhuXia requested changes
shall we take the chance to update some of the links?

2022-03-14 16:08 UTC, FuhuXia commented
should we take the chance to update the links?
[Suggest a new dataset](https://explore.data.gov/nominate) and see what others have suggested
Contribute code or [suggest a change](https://github.com/GSA/data.gov/issues?labels=&milestone=&page=1&state=open) on Github
Ask a general question at the [Open Data Stack Exchange](https://opendata.stackexchange.com/) and tag it with “data.gov”
Send an [email](https://www.data.gov/contact#question)

2022-03-14 16:18 UTC, jbrown-xentity commented on www.data.gov/catalog-help.md
> +- Send an [email](https://www.data.gov/contact#question)
Agreed. We don't monitor stack exchange, so remove that one. Also remove suggest a new dataset.
Add the data.gov/contact form. Keep email. change contribute code or suggest change link to the https://github.com/gsa/datagov-deploy repo, unless @mogul still wants to change the names...

2022-03-14 16:20 UTC, nickumia-reisys commented on www.data.gov/catalog-help.md
> +- Send an [email](https://www.data.gov/contact#question)
Sure.. did you have specific updates in mind?  I'm not sure which links aren't relevant anymore.

2022-03-15 16:47 UTC, jbrown-xentity approved these changes

2022-03-15 18:50 UTC, FuhuXia approved these changes

2022-03-15 18:51 UTC, merged